### ISSUE TITLE
Compare with native Magento asynchronous operation

### ISSUE THREAD

**Issue by onlinebizsoft** [aligent/magento-async-events#56]
What is the main difference or advantage of this one when we compare with this interface built-in Magento ?
https://developer.adobe.com/commerce/php/development/components/async-operations/

**Comment by onlinebizsoft** [comment]
@gowrizrh

**Comment by gowrizrh** [comment]
@onlinebizsoft The `Magento\Framework\Async\DeferredInterface` in the framework is just a nice abstraction to wrap a task that you can call or perform later. Meaning, they're still in the same process where it was set up.

Async Events aim to process events outside of your "main" process. It's similar to event observers, except the observer code is executed in a completely different php process.

The de facto use case is webhooks or event delivery.

**Comment by onlinebizsoft** [comment]
@gowrizrh thanks for your feedback, I have overlooked at previously and didn't realized the difference.

**Comment by onlinebizsoft** [comment]
@gowrizrh sorry, I have another silly question again. How do you compare this implementation with native Magento message queue? Basically we can observe an event and push to queue then have a consumer to process it outside "main" thread

**Comment by gowrizrh** [comment]
@onlinebizsoft The module is in a way declarative. You define the event and the payload. And you choose where you want to dispatch it and the code is executed when the event is dispatched. The advantage is there when you have a lot of consumers and even so when a lot of events.

On top of that, it handles failures with retries and exponential backoff. And replaying it again if we want. That also provides us with observability because events are indexed into Elasticsearch. See #28
